name: Ejecutar Script de Actualizacion de Listas de Estudiantes

on:
  schedule:
    # Ejecutar a las 4:30 AM hora de Perú (UTC-5) de lunes a viernes
    # En GitHub Actions se usa UTC, por lo que 4:30 AM en Perú es 9:30 AM UTC
    # Solo en meses de marzo (3) a diciembre (12)
    - cron: "30 9 * 3-12 1-5"

  # Permite la ejecución manual para pruebas
  workflow_dispatch:

jobs:
  ejecutar-script-actualizacion-listas-estudiantes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar dependencias
        run: npm install # ✅ Usa npm install - más permisivo

      - name: Ejecutar script de Actualizacion de listas de estudiantes con ts-node
        run: |
          echo "Ejecutando script de Actualizacion de listas de estudiantes..."
          npx ts-node ./src/jobs/asistenciaEscolar/SetListasDeEstudiantes.ts
        env:
          # Variables de Google Drive
          RDP01_GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          RDP01_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          RDP01_GOOGLE_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_PROJECT_ID }}
          RDP01_GOOGLE_DRIVE_ROOT_SHARED_FOLDER_ID: ${{ secrets.RDP01_GOOGLE_DRIVE_ROOT_SHARED_FOLDER_ID }}

          # Variables de PostgreSQL (RDP02)
          RDP02_INS1_DATABASE_URL: ${{ secrets.RDP02_INS1_DATABASE_URL }}
          RDP02_INS2_DATABASE_URL: ${{ secrets.RDP02_INS2_DATABASE_URL }}
          RDP02_INS3_DATABASE_URL: ${{ secrets.RDP02_INS3_DATABASE_URL }}

          # Variables de MongoDB (RDP03)
          RDP03_INS1_DATABASE_URL: ${{ secrets.RDP03_INS1_DATABASE_URL }}
          RDP03_INS2_DATABASE_URL: ${{ secrets.RDP03_INS2_DATABASE_URL }}
          RDP03_INS3_DATABASE_URL: ${{ secrets.RDP03_INS3_DATABASE_URL }}
          RDP03_INS4_DATABASE_URL: ${{ secrets.RDP03_INS4_DATABASE_URL }}
          RDP03_INS5_DATABASE_URL: ${{ secrets.RDP03_INS5_DATABASE_URL }}

          # Variables de Vercel Blobs
          RDP04_VERCEL_BLOB_INS1_READ_WRITE_TOKEN: ${{ secrets.RDP04_VERCEL_BLOB_INS1_READ_WRITE_TOKEN }}
          RDP04_VERCEL_BLOB_INS2_READ_WRITE_TOKEN: ${{ secrets.RDP04_VERCEL_BLOB_INS2_READ_WRITE_TOKEN }}
          RDP04_VERCEL_BLOB_INS3_READ_WRITE_TOKEN: ${{ secrets.RDP04_VERCEL_BLOB_INS3_READ_WRITE_TOKEN }}
          RDP04_VERCEL_BLOB_INS4_READ_WRITE_TOKEN: ${{ secrets.RDP04_VERCEL_BLOB_INS4_READ_WRITE_TOKEN }}
          RDP04_VERCEL_BLOB_INS5_READ_WRITE_TOKEN: ${{ secrets.RDP04_VERCEL_BLOB_INS5_READ_WRITE_TOKEN }}

          # Variables de Redis
          RDP05_INS1_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS1_REDIS_BD_BASE_URL_API }}
          RDP05_INS1_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS1_REDIS_BD_TOKEN_FOR_API }}
          RDP05_INS2_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS2_REDIS_BD_BASE_URL_API }}
          RDP05_INS2_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS2_REDIS_BD_TOKEN_FOR_API }}
          RDP05_INS3_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS3_REDIS_BD_BASE_URL_API }}
          RDP05_INS3_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS3_REDIS_BD_TOKEN_FOR_API }}

          # Variables de Email
          SE01_SIASIS_EMAIL_USER: ${{ secrets.SE01_SIASIS_EMAIL_USER }}
          SE01_SIASIS_EMAIL_APPLICATION_PASSWORD: ${{ secrets.SE01_SIASIS_EMAIL_APPLICATION_PASSWORD }}

          # Variables de Entorno
          ENTORNO: ${{ secrets.ENTORNO }}
